/* KYOHO / 巨歩 — playable prototype 0.1.0. No third-party JS dependencies. */
(()=>{'use strict';
const $=id=>document.getElementById(id),SIZES=[.18,.6,3,12],VERSION='0.2.0',SAVE_KEY='kyoho-save-v1';
const isTouch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;if(isTouch)document.body.classList.add('touch');
const options={labels:true,sound:true,quality:'standard',reduced:matchMedia('(prefers-reduced-motion:reduce)').matches,contour:false,dusk:false};
let saved=null;try{saved=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(saved?.version===1&&saved.options)Object.assign(options,saved.options)}catch{}
let renderer;try{renderer=new TinyGL($('world'))}catch(e){$('fatal').classList.remove('hidden');$('fatalMessage').textContent=e.message;return;}
const terrain=new JapanTerrain(renderer),demoMeshes=createDemoTerrain(renderer),cube=cubeMesh(renderer),sphere=sphereMesh(renderer),ring=ringMesh(renderer),water=planeMesh(renderer),ribbon=renderer.mesh([],null,true),particleMesh=renderer.mesh([],null,true);
const STATS=saved?.stats&&typeof saved.stats==='object'?saved.stats:{demo:{distance:0,best:0},japan:{distance:0,best:0}};
for(const mode of['demo','japan']){if(!STATS[mode])STATS[mode]={distance:0,best:0};for(const f of['distance','best'])if(!Number.isFinite(STATS[mode][f])||STATS[mode][f]<0)STATS[mode][f]=0;}
const placesWorld=new JapanPlaces(renderer,cube,ring);
const S={mode:'demo',started:false,modal:null,pending:null,auto:false,lat:36.26,lon:137.66,x:8,z:20,y:0,vy:0,vx:0,vz:0,ground:0,grounded:true,size:.6,sizeIndex:1,targetSize:.6,heading:0,camYaw:0,camPitch:.24,camDist:1,camEye:[0,5,5],energy:1,gait:0,time:0,distance:0,flow:0,gates:0,routeIndex:0,challenge:false,remaining:90,challengeDistance:0,challengeScore:0,region:DESTINATIONS[0],lastFoot:0,jumpBuffer:0,tutorial:0,startedAt:0,gliding:false,loadingMove:false,photo:false};
S.ground=Math.max(0,demoHeight(S.x,S.z));S.y=S.ground;
let frame=frameAt(S.lat,S.lon),route=[],particles=[],pulses=[],lastNow=performance.now()/1000,lastUI=0,lastSave=0,toastUntil=0,tipUntil=0,photoBlob=null,photoURL=null,didJump=false,didSize=false,stoppedForData=false;
let autoResolution=1;
let fpsCounter=0,fpsElapsed=0,currentFps=60,lastInput=0;
const input={keys:new Set,joyX:0,joyY:0,jump:false,dash:false,drag:false,dragId:null,lastX:0,lastY:0};
const TITLES=['谷を越える','稜線に乗る','小さくなって、くぐる','空へ飛び出す','山の向こうへ','地形をつなぐ','もう一度、小さく','その先の光'];
function heightLabel(h){return h>=1?(h.toFixed(h<10?1:0).replace('.0','')+' km'):(Math.round(h*1000)+' m')}
function modal(id){if(id){$('placeLabels').hidden=true;$('townStatus').hidden=true;}for(const el of document.querySelectorAll('.modal'))el.classList.toggle('hidden',el.id!==id);S.modal=id||null;input.keys.clear();input.joyX=input.joyY=0;input.jump=input.dash=false;S.auto=false;audio.quiet(!!id);if(id==='mapModal')drawAtlas();if(id==='settings')updateOptions();}
function showToast(big,small='DISCOVERY',duration=3){$('toast').querySelector('.big').textContent=big;$('toast').querySelector('.small').textContent=small;$('toast').classList.add('show');toastUntil=S.time+duration;}
function tip(text,duration=5){$('tip').textContent=text;$('tip').classList.remove('hidden');tipUntil=S.time+duration;}
function setSize(i,quiet=false){i=clamp(i,0,3);if(S.sizeIndex===i)return;S.sizeIndex=i;S.targetSize=SIZES[i];didSize=true;for(const b of $('sizeButtons').children)b.classList.toggle('active',+b.dataset.size===i);if(!quiet){showToast(heightLabel(S.targetSize)+' の、あなた。','SCALE SHIFT');audio.chime(2);if(S.targetSize<.65)tip('同じ場所、同じ地形。変わったのは、自分だけ。',4)}save();}
function showHUD(){S.started=true;S.startedAt=S.time;$('title').classList.add('hidden');$('bgCaption').classList.add('hidden');$('hud').classList.remove('hidden');$('touchControls').classList.remove('hidden');$('targetLabel').classList.remove('hidden');$('world').focus({preventScroll:true});updateUI();}
function stopMotion(){S.vx=S.vz=S.vy=0;S.energy=1;S.grounded=true;input.keys.clear();input.jump=false;input.dash=false;S.auto=false;S.camEye=[0,S.y+S.size*2.5,S.size*4.5];pulses=[];particles=[];}
function course(){route=[];S.routeIndex=0;const offsets=[[1,-4],[-2,-10],[-5,-19],[-15,-29],[-2,-38],[4,-49],[-9,-57],[0,-68]];
 for(let i=0;i<offsets.length;i++){const x=offsets[i][0],z=offsets[i][1];let o={id:i,title:TITLES[i],small:i===2||i===6,cleared:false};if(S.mode==='demo'){o.x=8+x;o.z=20+z;}else{const ll=offsetLL(S.region.lat,S.region.lon,x*.42,z*.42);o.lat=ll[0];o.lon=ll[1];}route.push(o)}
 $('routePills').innerHTML=route.map(()=>'<span></span>').join('');
}
function startDemo(reset=true){terrain.enabled=false;S.pending=null;modal(null);S.mode='demo';S.challenge=false;S.remaining=90;S.x=8;S.z=20;S.heading=S.camYaw=0;S.camPitch=.24;S.size=S.targetSize=.6;S.sizeIndex=1;S.ground=Math.max(0,demoHeight(S.x,S.z));S.y=S.ground;S.distance=0;S.flow=0;S.gates=0;S.loadingMove=false;stopMotion();course();showHUD();for(const b of $('sizeButtons').children)b.classList.toggle('active',+b.dataset.size===1);audio.start();showToast('まずは、あの光まで。','FICTIONAL TRAINING ISLAND',3.5);tip(isTouch?'左のスティックで移動。右の空いている画面をなぞると視点が変わります。':'Wで走り出す。J / Lで左右、I / Kで上下を見渡せます。ドラッグも使えます。',7);save();}
function startJapan(destination=DESTINATIONS[0]){S.pending={...destination,startedAt:S.time};terrain.enabled=true;terrain.zoom=terrain.selectZoom(destination.size||.6);terrain.update(destination.lat,destination.lon,destination.size||.6,S.time,true);$('loadTitle').textContent=destination.name+'へ。';$('loadError').classList.add('hidden');$('retryLoad').classList.add('hidden');$('loadProgress').firstElementChild.style.width='3%';modal('loading');audio.start();}
function finishJapan(){const dest=S.pending;if(!dest)return;let h=terrain.sample(dest.lat,dest.lon);if(!h)return;S.mode='japan';S.region=dest;S.lat=dest.lat;S.lon=dest.lon;S.heading=S.camYaw=dest.heading||0;S.camPitch=.25;S.size=S.targetSize=dest.size||.6;S.sizeIndex=SIZES.indexOf(S.size);S.y=S.ground=h.h;S.distance=0;S.gates=0;S.flow=0;S.challenge=false;S.loadingMove=false;S.pending=null;stopMotion();course();modal(null);showHUD();for(const b of $('sizeButtons').children)b.classList.toggle('active',+b.dataset.size===S.sizeIndex);placesWorld.lastScan=-Infinity;showToast(dest.name+'の、向こうへ。','REAL TERRAIN / GSI',4);tip('ここからは、実際の日本の地形。高さは誇張していません。',6);save();}
function pollLoading(){if(!S.pending)return;const d=S.pending;terrain.update(d.lat,d.lon,d.size||.6,S.time);const p=terrain.progress(),elapsed=S.time-d.startedAt;const h=terrain.sample(d.lat,d.lon);$('loadProgress').firstElementChild.style.width=Math.max(3,p.ready/p.total*100)+'%';$('loadStats').textContent=`取得 ${p.ready} / ${p.total} タイル · 通信 ${(p.bytes/1048576).toFixed(1)} MB · ${p.failed?'接続失敗 '+p.failed+' 件':'必要な範囲から読み込み中'}`;
 if(h&&(p.ready>=5||elapsed>8)){finishJapan();return}if((p.failed>0&&elapsed>3)||elapsed>13){$('loadError').classList.remove('hidden');$('retryLoad').classList.remove('hidden');}}
function getGround(x,z){if(S.mode==='demo')return{h:Math.max(0,demoHeight(x,z)),valid:true,zoom:0};return terrain.sample(x,z);}
function nearby(east,south){return S.mode==='demo'?getGround(S.x+east,S.z+south):(()=>{const ll=offsetLL(S.lat,S.lon,east,south);return getGround(ll[0],ll[1])})();}
function gatePosition(g){if(S.mode==='demo'){return[g.x-S.x,Math.max(0,demoHeight(g.x,g.z))+.75,g.z-S.z]}const v=terrain.sample(g.lat,g.lon);if(!v)return null;return localGeo(g.lat,g.lon,v.h+.75,frame);}
function gateDistance(g){return S.mode==='demo'?Math.hypot(g.x-S.x,g.z-S.z):haversine(S.lat,S.lon,g.lat,g.lon)}
function nextGate(){return route[S.routeIndex]||null}
function requestJump(){if(!S.started||S.modal)return;S.jumpBuffer=.18;audio.start();}
function jump(){const grav=2.1+S.size*1.4;S.vy=Math.sqrt(2*grav*S.size*2.6);S.grounded=false;S.jumpBuffer=0;didJump=true;spawnBurst([0,S.y+.03,0],S.size,10);audio.jump();}
function spawnBurst(p,size,count=8){for(let i=0;i<count;i++)particles.push({p:[p[0],p[1],p[2]],v:[(Math.random()-.5)*size*.8,Math.random()*size*.5,(Math.random()-.5)*size*.8],age:0,life:.7+Math.random()*.7,size:size*(.01+Math.random()*.014)});if(particles.length>100)particles.splice(0,particles.length-100)}
function addPulse(){pulses.push({p:[0,S.ground+.035,0],age:0,size:S.size});if(pulses.length>14)pulses.shift();}
function collectGate(g,pos){if(g.small&&S.size>.75){if(S.time-(g.warnAt||-100)>3){tip('小さな光です。180 m または 600 m に縮んで、もう一度。',4);g.warnAt=S.time;}return;}
 g.cleared=true;S.routeIndex++;S.gates++;S.energy=1;S.flow=Math.min(100,S.flow+19);S.challengeScore+=100+(g.small?60:0)+Math.round(S.flow);spawnBurst(pos,Math.max(.5,S.size),28);addPulse();audio.chime(S.routeIndex);$('routePills').children[S.routeIndex-1]?.classList.add('done');
 if(S.routeIndex===route.length){if(S.challenge){S.challengeScore+=Math.round(S.remaining*10);finishChallenge();}else{showToast('山の向こうに、また世界。','ALL LIGHTS CONNECTED',4);tip('地図から別の土地へ。あるいは、目的地を決めずに走ろう。',7);}}
 else{showToast(g.title+'。',`LIGHT ${S.routeIndex} / ${route.length}`,2.1);if(nextGate().small)tip('次は小さな光。600 m 以下に縮むと、くぐれます。',5);}
 save();}
function startChallenge(){if(!S.started){startDemo()}modal(null);if(S.mode==='demo'){S.x=8;S.z=20;}else{S.lat=S.region.lat;S.lon=S.region.lon;}S.size=S.targetSize=.6;S.sizeIndex=1;S.camYaw=S.heading=0;S.camPitch=.24;let h=S.mode==='demo'?getGround(S.x,S.z):getGround(S.lat,S.lon);S.y=S.ground=h?h.h:0;stopMotion();course();S.challenge=true;S.remaining=90;S.challengeDistance=S.distance;S.challengeScore=0;S.flow=0;for(const b of $('sizeButtons').children)b.classList.toggle('active',+b.dataset.size===1);showToast('光を、つなげ。','90 SECONDS / START',3);tip('光を順番にくぐる。小さな光は600 m 以下。メニュー中と地形の取得待ちは時計が止まります。',6);audio.chime(0);}
function finishChallenge(){if(!S.challenge)return;S.challenge=false;const count=S.routeIndex,score=S.challengeScore+Math.round((S.distance-S.challengeDistance)*3),best=STATS[S.mode].best||0;STATS[S.mode].best=Math.max(best,score);$('resultGrade').textContent=count===8?'BEYOND':count>=5?'FLOW':count>=2?'STRIDE':'FIRST STEP';$('resultTitle').textContent=count===8?'山脈が、道になった。':'この先にも、山がある。';$('resultGates').textContent=count+' / '+route.length;$('resultDistance').textContent=(S.distance-S.challengeDistance).toFixed(1);$('resultScore').textContent=score;$('resultText').textContent=(score>best?'新しい自己ベスト。':'自己ベスト '+best+'。')+' 大きく駆け、小さくくぐる。次はどんな軌跡になる？';$('resultMode').textContent=S.mode==='demo'?'架空の練習島での記録。実際の日本の移動記録ではありません。':S.region.name+' / 国土地理院の標高データを加工して表示したステージでのゲーム記録。';modal('result');save();}
function updateMovement(dt){if(!S.started||S.modal)return;const ease=1-Math.exp(-dt*3.8);S.size=Math.exp(mix(Math.log(S.size),Math.log(S.targetSize),ease));if(Math.abs(S.size-S.targetSize)<.001)S.size=S.targetSize;
 if(S.mode==='japan')terrain.update(S.lat,S.lon,S.size,S.time);
 const k=input.keys;S.camYaw+=((k.has('KeyL')?1:0)-(k.has('KeyJ')?1:0))*1.5*dt;S.camPitch=clamp(S.camPitch+((k.has('KeyK')?1:0)-(k.has('KeyI')?1:0))*.8*dt,-.07,.90);let ix=(k.has('KeyD')||k.has('ArrowRight')?1:0)-(k.has('KeyA')||k.has('ArrowLeft')?1:0)+input.joyX,iz=(k.has('KeyW')||k.has('ArrowUp')||S.auto?1:0)-(k.has('KeyS')||k.has('ArrowDown')?1:0)-input.joyY;const len=Math.hypot(ix,iz);if(len>1){ix/=len;iz/=len}
 const move=Math.min(1,len),sn=Math.sin(S.camYaw),cs=Math.cos(S.camYaw),wx=ix*cs+iz*sn,wz=ix*sn-iz*cs;const boosting=(input.dash||k.has('ShiftLeft')||k.has('ShiftRight'))&&S.energy>.03&&move>.1;
 let ahead=nearby(wx*S.size*.75,wz*S.size*.75),slope=ahead?(S.ground-ahead.h)/Math.max(S.size*.75,.1):0;
 const base=S.size*2.65+.12,speed=base*(boosting?2.12:1)*clamp(1+slope*.30,.72,1.45);const accel=1-Math.exp(-dt*(S.grounded?3.7:1.8));S.vx=mix(S.vx,wx*speed,accel);S.vz=mix(S.vz,wz*speed,accel);if(move<.01){S.vx*=Math.exp(-dt*3);S.vz*=Math.exp(-dt*3)}
 if(boosting)S.energy=Math.max(0,S.energy-dt*.17);else S.energy=Math.min(1,S.energy+dt*(S.grounded?.12:.045));
 let dx=S.vx*dt,dz=S.vz*dt,newX=S.x+dx,newZ=S.z+dz,oldLat=S.lat,oldLon=S.lon,newLL=offsetLL(S.lat,S.lon,dx,dz);
 let ground=S.mode==='demo'?getGround(newX,newZ):getGround(newLL[0],newLL[1]);
 S.loadingMove=!ground;
 if(!ground){S.vx=S.vz=0;dx=dz=0;if(!stoppedForData){tip('この先の実地形を取得しています。取得できるまで移動を止めています。',4);stoppedForData=true}placesWorld.update(S,terrain,0);return;}stoppedForData=false;
 if(S.mode==='demo'){S.x=newX;S.z=newZ;if(Math.abs(S.x)>61||S.z< -77||S.z>44){S.x=clamp(S.x,-60,60);S.z=clamp(S.z,-76,43);S.vx*=-.3;S.vz*=-.3;tip('ここは架空の練習島。日本地図から、実際の日本へ移れます。',5)}}else{S.lat=newLL[0];S.lon=newLL[1];if(S.lat<20||S.lat>46.7||S.lon<122||S.lon>150){S.lat=clamp(S.lat,20,46.7);S.lon=clamp(S.lon,122,150);S.vx=S.vz=0;tip('この版の探索範囲の端です。地図から別の場所へ移れます。',5)}}
 const travelled=S.mode==='demo'?Math.hypot(dx,dz):haversine(oldLat,oldLon,S.lat,S.lon);S.distance+=travelled;STATS[S.mode].distance+=travelled;S.ground=ground.h;
 for(let p of particles){p.p[0]-=dx;p.p[2]-=dz}for(let p of pulses){p.p[0]-=dx;p.p[2]-=dz}
 if(Math.hypot(S.vx,S.vz)>.06){let desired=Math.atan2(S.vx,-S.vz),difference=Math.atan2(Math.sin(desired-S.heading),Math.cos(desired-S.heading));S.heading+=difference*(1-Math.exp(-dt*9));}
 let g=2.1+S.size*1.4,held=input.jump||k.has('Space');S.gliding=!S.grounded&&held&&S.vy<.1;
 if(S.jumpBuffer>0&&S.grounded)jump();S.jumpBuffer=Math.max(0,S.jumpBuffer-dt);
 if(!S.grounded){S.vy-=g*dt*(S.gliding?.14:1);if(S.gliding)S.vy=Math.max(S.vy,-S.size*.35-.12);S.y+=S.vy*dt;if(S.y<=S.ground){S.y=S.ground;S.grounded=true;if(S.vy<-.2){addPulse();spawnBurst([0,S.y+.02,0],S.size,16);audio.land(S.size)}S.vy=0;}}
 else{if(S.y-S.ground>S.size*.28){S.grounded=false;S.vy=0}else S.y=S.ground;}
 if(S.y<S.ground){S.y=S.ground;S.vy=Math.max(0,S.vy);S.grounded=true;}
 let actualSpeed=Math.hypot(S.vx,S.vz);S.gait+=dt*clamp(actualSpeed/Math.max(S.size,.1)*2.9,0,18);
 if(S.grounded&&actualSpeed>S.size*.4){const foot=Math.floor(S.gait/Math.PI);if(foot!==S.lastFoot){S.lastFoot=foot;addPulse();audio.step(S.size);spawnBurst([0,S.ground+.01,S.size*.08],S.size,4)}}
 if(move>.2&&S.grounded)S.flow=clamp(S.flow+dt*4,0,100);else S.flow=Math.max(0,S.flow-dt*1.8);
 frame=frameAt(S.lat,S.lon);
 const gate=nextGate();if(gate){const p=gatePosition(gate),rad=gate.small?.58:Math.max(.85,S.size*.8);if(p){const a=[0,S.y+S.size*.55,0],old=[-dx,a[1]-S.vy*dt,-dz],ab=V.sub(a,old),ap=V.sub(p,old),t=clamp(V.dot(ap,ab)/(V.dot(ab,ab)||1),0,1),closest=V.add(old,V.mul(ab,t));if(Math.hypot(...V.sub(closest,p))<rad+Math.min(S.size*.23,.65))collectGate(gate,p);}}
 if(S.challenge&&!S.loadingMove){S.remaining=Math.max(0,S.remaining-dt);if(S.remaining===0)finishChallenge();}
 if(S.time-S.startedAt>9&&S.tutorial===0&&!S.modal){S.tutorial=1;tip(isTouch?'「跳ぶ」を長押し。空中では風に乗って、滑空します。':'Spaceで跳ぶ。空中で長押しすると、風に乗って滑空します。',6)}
 if(S.time-S.startedAt>24&&S.tutorial===1&&!didSize){S.tutorial=2;tip('身長を切り替えてみよう。同じ谷の広さが、まったく違って見えます。',6)}
 placesWorld.update(S,terrain,dt);
 if(actualSpeed>.1)audio.wind(clamp(actualSpeed/(S.size*4),0,1),S.gliding);
}
function localBody(p){const c=Math.cos(S.heading),s=Math.sin(S.heading),h=S.size;return[(c*p[0]-s*p[2])*h,S.y+p[1]*h,(s*p[0]+c*p[2])*h]}
function renderAvatar(){const r=renderer,h=S.size,run=clamp(Math.hypot(S.vx,S.vz)/(h*2),0,1),phase=S.gait,bob=S.grounded?Math.abs(Math.sin(phase))*.025*run:0;
 const white=[.91,.91,.79,1],shade=[.48,.66,.60,1],orange=[.96,.49,.24,1],dark=[.075,.18,.19,1],light=[.78,.99,.89,1];
 const block=(p,s,color,yaw=-S.heading,rx=0,em=0)=>r.draw(cube,M.trs(localBody(p),s.map(v=>v*h),yaw,rx),color,1,0,em);
 const ball=(p,s,color,em=0)=>r.draw(sphere,M.trs(localBody(p),[s*h,s*h,s*h]),color,1,0,em);
 const limb=(a,b,w,color)=>r.draw(cube,M.segment(localBody(a),localBody(b),w*h,w*h*.88),color,1);
 let lean=S.grounded?run*.10:.10;
 block([0,.645+bob,-lean*.15],[.235,.30,.135],white,-S.heading,-lean);
 block([0,.49+bob,0],[.215,.09,.145],shade);
 block([0,.72+bob,.087],[.15,.21,.06],dark);
 block([0,.77+bob,-.077],[.16,.047,.024],orange);
 ball([0,.907+bob,-.018],.185,white,.1);
 block([0,.91+bob,-.099],[.14,.047,.029],dark);
 block([0,.92+bob,-.116],[.104,.012,.009],light,-S.heading,0,.8);
 block([0,.818+bob,0],[.13,.065,.13],orange);
 for(let side of[-1,1]){let a=phase+(side<0?Math.PI:0),step=Math.sin(a)*run,knee=[side*.09,.265+Math.max(0,Math.sin(a))*.055*run,step*.16],ankle=[side*.09,.045+Math.max(0,Math.sin(a))*.115*run,step*.28];if(!S.grounded){knee=[side*.105,.26,.1+(side+1)*.04];ankle=[side*.11,.07,.18+(side+1)*.06]}
 let hip=[side*.08,.50+bob,0];limb(hip,knee,.085,white);ball(knee,.087,shade);limb(knee,ankle,.069,white);block([ankle[0],ankle[1],ankle[2]-.024],[.087,.062,.14],dark);block([ankle[0],ankle[1]+.018,ankle[2]-.06],[.088,.021,.051],orange);
 let shoulder=[side*.16,.757+bob,0],elbow=[side*.20,.61+bob,-step*.12],hand=[side*.18,.52+bob,-step*.27-.07];if(S.gliding){elbow=[side*.34,.77,-.02];hand=[side*.53,.80,-.11]}else if(!S.grounded){elbow=[side*.27,.80,-.02];hand=[side*.37,.88,-.1]}
 ball(shoulder,.087,white);limb(shoulder,elbow,.067,white);ball(elbow,.07,shade);limb(elbow,hand,.058,white);ball(hand,.077,orange);
 }
 const data=[],points=[];const length=S.gliding?1.4:.8;for(let i=0;i<=12;i++){let t=i/12;for(let side of[-1,1]){let width=S.gliding?(.56*(1-t)+.04):.045;let p=localBody([side*width+Math.sin(S.time*4-t*9)*.045*t,.805+bob+Math.sin(S.time*3-t*8)*.045*t-t*.18,.09+t*length]);points.push(p)}}for(let i=0;i<12;i++){let a=i*2;for(let v of[a,a+1,a+2,a+1,a+3,a+2])vertex(data,points[v],[0,.8,.3],[1,1-(v%3)*.055,1]);}r.update(ribbon,data);r.draw(ribbon,r.I,[.97,.48,.25,.92],1,0,.08);
}
function renderGates(){const r=renderer;for(let i=Math.max(0,S.routeIndex-1);i<Math.min(route.length,S.routeIndex+3);i++){const g=route[i],pos=gatePosition(g);if(!pos)continue;const dist=Math.hypot(pos[0],pos[2]);if(dist>Math.max(70,S.size*80))continue;const active=i===S.routeIndex,rad=g.small?.58:Math.max(.85,active?S.size*.8:.85),color=g.cleared?[.55,.81,.7,.20]:active?[1,.72,.36,1]:[.63,.82,.70,.35];const yaw=-Math.atan2(pos[0],pos[2]);
 r.draw(ring,M.trs(pos,[rad,rad,rad],yaw),color,3,0,.20);if(active){r.draw(ring,M.trs(pos,[rad*1.065,rad*1.065,rad],yaw),[1,.79,.48,.12],3);r.draw(ring,M.trs(pos,[rad*.94,rad*.94,rad],yaw),[1,.81,.53,.16],3);let pulse=.02*Math.sin(S.time*3);r.draw(sphere,M.trs([pos[0],pos[1]+rad+.18,pos[2]],[.12+pulse,.12+pulse,.12+pulse]),[1,.85,.56,1],3,0,.4);}}
}
function renderParticles(dt){const data=[],right=[Math.cos(S.camYaw),0,Math.sin(S.camYaw)],up=[0,1,0];particles=particles.filter(p=>p.age<p.life);for(let p of particles){p.age+=dt;for(let j=0;j<3;j++)p.p[j]+=p.v[j]*dt;p.v[1]-=dt*.04;let size=p.size*(1-p.age/p.life),rr=V.mul(right,size),uu=V.mul(up,size),pts=[V.sub(V.sub(p.p,rr),uu),V.add(V.sub(p.p,uu),rr),V.add(V.add(p.p,rr),uu),V.add(V.sub(p.p,rr),uu)];for(let i of[0,1,2,0,2,3])vertex(data,pts[i],[0,1,0],[1,.85,.54]);}renderer.update(particleMesh,data);renderer.draw(particleMesh,renderer.I,[1,.89,.66,.56],3,0,.4);pulses=pulses.filter(p=>p.age<1.2);for(let p of pulses){p.age+=dt;let radius=p.size*(.08+p.age*1.1);renderer.draw(ring,M.trs(p.p,[radius,radius,radius],0,Math.PI/2),[.82,.90,.69,(1-p.age/1.2)*.19],3);}}
function render(dt){const r=renderer;frame=frameAt(S.lat,S.lon);let title=!S.started,heading=title?.30+Math.sin(S.time*.055)*.16:S.camYaw;let pitch=title?.29:S.camPitch;let speed=Math.hypot(S.vx,S.vz);let dist=S.size*(title?7.2:4.7);let fov=(options.reduced?58:58+clamp(speed/(S.size*5),0,1)*8)*RAD;const cy=S.y+S.size*.82;let eye=[-Math.sin(heading)*Math.cos(pitch)*dist,cy+Math.sin(pitch)*dist,Math.cos(heading)*Math.cos(pitch)*dist];let gh=nearby(eye[0],eye[2]);if(gh)eye[1]=Math.max(eye[1],gh.h+S.size*.37);if(title)eye[1]+=S.size*.30;let blend=1-Math.exp(-dt*6);S.camEye=S.camEye.map((v,i)=>mix(v,eye[i],blend));const at=[0,cy,0];
 const fog=S.mode==='demo'?28:Math.max(10,S.size*35);r.resize(innerWidth,innerHeight,options.quality==='light'?Math.min(.72,1000/innerWidth):Math.min(devicePixelRatio,1.5,1440/innerWidth)*autoResolution);r.begin(S.camEye,at,frame,[S.x,0,S.z],options.reduced?0:S.time,S.size,{fov,fog,contour:options.contour,dusk:options.dusk?1:0,ground:S.y});
 r.draw(water,r.I,[1,1,1,1],2,0);
 if(S.mode==='demo'){const visible=demoMeshes.filter(m=>Math.hypot(m.cx-S.x,m.cz-S.z)<Math.max(48,S.size*15)&&((m.cx-S.x)*Math.sin(heading)-(m.cz-S.z)*Math.cos(heading))>-16).sort((a,b)=>Math.hypot(a.cx-S.x,a.cz-S.z)-Math.hypot(b.cx-S.x,b.cz-S.z));for(const mesh of visible)r.draw(mesh,r.I,[1,1,1,1],0,2);}else terrain.draw(S.lat,S.lon);
 placesWorld.draw(S,terrain,frame);if(S.started)renderGates();renderAvatar();renderParticles(S.modal?0:dt);
 if(S.started){const g=nextGate(),pos=g?gatePosition(g):null,label=$('targetLabel');if(pos){const p=r.project([pos[0],pos[1]+(g.small?.9:Math.max(1.1,S.size*1.1)),pos[2]]);if(p.w>0){label.classList.remove('hidden');label.style.left=clamp(p.x,70,innerWidth-70)+'px';label.style.top=clamp(p.y,innerHeight<520?88:100,innerHeight-155)+'px';label.querySelector('b').textContent=g.small?'小さな光 · 600 m 以下':'次の光';label.querySelector('span.mono').textContent=gateDistance(g).toFixed(1)+' km';}else label.classList.add('hidden');}else label.classList.add('hidden');}
}
function updateUI(){if(!S.started)return;$('modeBadge').textContent=S.mode==='demo'?'TRAINING / 架空の練習島':'REAL JAPAN / 実地形ストリーミング';$('regionName').textContent=S.mode==='demo'?'架空の練習島':S.region.name+'からの旅';$('distance').textContent=S.distance.toFixed(1);$('speedNum').textContent=Math.hypot(S.vx,S.vz).toFixed(1);$('heightReadout').innerHTML='<span class="mono">'+(S.size>=1?S.size.toFixed(1).replace('.0',''):Math.round(S.size*1000))+'</span><small>'+(S.size>=1?'km':'m')+'</small>';$('movementState').textContent=S.loadingMove?'WAITING FOR TERRAIN':S.gliding?'ON THE WIND':!S.grounded?'AIRBORNE':S.ground<.005?'SEA STRIDE':'GROUND FLOW';$('energy').firstElementChild.style.width=(S.energy*100)+'%';let b=(S.camYaw/RAD%360+360)%360,dirs=['N','NE','E','SE','S','SW','W','NW'];$('bearing').textContent=dirs[Math.round(b/45)%8]+' · '+Math.round(b).toString().padStart(3,'0')+'°';$('altitude').textContent=Math.round(S.ground*1000).toLocaleString()+' m';$('objectiveMode').textContent=S.challenge?'90 SECOND CHALLENGE':'FREE ROAM';const ng=nextGate();$('objectiveTitle').textContent=ng?ng.title+'。':'どこへでも。';$('objectiveDesc').textContent=ng?`次の光まで ${gateDistance(ng).toFixed(1)} km · ${S.routeIndex} / ${route.length}`:'全ての光を発見。次の風景を探そう。';$('timer').classList.toggle('hidden',!S.challenge);$('timer').querySelector('span').textContent=S.remaining.toFixed(1);$('timer').style.color=S.remaining<15?'var(--accent)':'var(--ink)';$('autoBtn').textContent=S.auto?'自動走行 ■':'自動走行';$('autoBtn').classList.toggle('on',S.auto);
 let ds=$('dataStatus');if(S.mode==='demo'){ds.classList.remove('warn');ds.textContent='練習島：架空の地形 / 通信不要';$('source').innerHTML='練習島：架空地形 / 日本の実地形ではありません';}else{const p=terrain.progress(),h=terrain.sample(S.lat,S.lon),meshSpacing=40075*Math.cos(S.lat*RAD)/2**terrain.renderZoom/terrain.quality*1000;ds.classList.toggle('warn',!!p.failed||!h||!h.valid);ds.textContent=`DEM10B系 · z${terrain.renderZoom} · 地形比率 1:1\n描画間隔 約${Math.round(meshSpacing)}m · ${p.ready}/${p.total}タイル${p.failed?' · 取得失敗 '+p.failed:''}${h&&!h.valid?' · 現在地は標高欠測':''}`;ds.style.whiteSpace='pre-line';$('source').innerHTML='<a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank" rel="noopener">国土地理院・地理院タイル（標高）</a>を加工 / <a href="https://www.gsi.go.jp/kihonjohochousa/kihonjohochousa41139.html" target="_blank" rel="noopener">山名・地名：国土地理院</a>';}
 placesWorld.updateLabels(S,terrain,frame,options.labels);drawMinimap();}
function drawMinimap(){const c=$('minimap'),g=c.getContext('2d'),w=c.width,h=c.height;g.clearRect(0,0,w,h);g.save();g.translate(w/2,h/2);const span=Math.max(20,S.size*24),scale=w/span;g.strokeStyle='#c4e1cf24';g.lineWidth=1;for(let r of[44,88,132]){g.beginPath();g.arc(0,0,r,0,Math.PI*2);g.stroke()}g.beginPath();g.moveTo(-140,0);g.lineTo(140,0);g.moveTo(0,-140);g.lineTo(0,140);g.stroke();
 for(const item of route){let p=S.mode==='demo'?[item.x-S.x,0,item.z-S.z]:localGeo(item.lat,item.lon,0,frame),x=p[0]*scale,y=p[2]*scale;if(Math.hypot(x,y)>120)continue;g.fillStyle=item.cleared?'#85b19e':item===nextGate()?'#f9be75':'#c8d7c8';g.beginPath();g.arc(x,y,item===nextGate()?6:3,0,Math.PI*2);g.fill()}
 if(S.mode==='japan')placesWorld.minimap(g,frame,scale);
 g.rotate(S.heading);g.fillStyle='#edf3dd';g.beginPath();g.moveTo(0,-12);g.lineTo(-6,6);g.lineTo(0,3);g.lineTo(6,6);g.closePath();g.fill();g.restore();g.font='17px sans-serif';g.fillStyle='#dcebdacc';g.textAlign='center';g.fillText('N',w/2,28);}
function drawAtlas(){const c=$('atlasCanvas'),rect=c.getBoundingClientRect();if(!rect.width)return;c.width=Math.round(rect.width*2);c.height=Math.round(rect.height*2);const g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#103138';g.fillRect(0,0,w,h);const minLon=122.5,maxLon=147.6,minLat=24,maxLat=46.5;let ratio=Math.min(w/((maxLon-minLon)*.80),h/(maxLat-minLat))*.92;const tx=lon=>w/2+(lon-(minLon+maxLon)/2)*ratio*.8,ty=lat=>h/2-((lat)-(minLat+maxLat)/2)*ratio;
 g.strokeStyle='#b9d8c918';g.lineWidth=1;for(let lon=125;lon<=145;lon+=5){g.beginPath();g.moveTo(tx(lon),0);g.lineTo(tx(lon),h);g.stroke()}for(let lat=25;lat<=45;lat+=5){g.beginPath();g.moveTo(0,ty(lat));g.lineTo(w,ty(lat));g.stroke()}
 for(const poly of JAPAN_COAST)for(const ring of poly){g.beginPath();ring.forEach((p,i)=>i?g.lineTo(tx(p[0]),ty(p[1])):g.moveTo(tx(p[0]),ty(p[1])));g.closePath();g.fillStyle='#476a60';g.fill();g.strokeStyle='#b0c2a876';g.lineWidth=1.4;g.stroke()}
 const labels=['daisetsu','alps','fuji','aso','ishizuchi','chokai','yanbaru'];for(const d of DESTINATIONS){let x=tx(d.lon),y=ty(d.lat);g.fillStyle=d.id===S.region.id&&S.mode==='japan'?'#f7c382':'#c5dcca';g.beginPath();g.arc(x,y,5,0,Math.PI*2);g.fill();if(labels.includes(d.id)){g.font='18px -apple-system,sans-serif';g.textAlign=d.id==='fuji'?'left':'right';g.fillStyle='#d9e7d8';g.fillText(d.name,x+(d.id==='fuji'?11:-11),y+5);}}
 if(S.mode==='japan'){g.strokeStyle='#f1bd76';g.lineWidth=2;g.beginPath();g.arc(tx(S.lon),ty(S.lat),12,0,Math.PI*2);g.stroke()}
 g.fillStyle='#bdd4c386';g.font='16px sans-serif';g.textAlign='left';g.fillText('JAPAN / CONCEPTUAL OVERVIEW',22,h-22);c._map={tx,ty};}
function populatePlaces(){$('places').innerHTML='';for(const d of DESTINATIONS){const b=document.createElement('button');b.innerHTML=`<span class="region">${d.region}</span><strong>${d.name} ↗</strong><small>${d.sub}</small>`;b.onclick=()=>startJapan(d);$('places').appendChild(b)}const details=document.createElement('details');details.className='town-destinations';const summary=document.createElement('summary');summary.textContent='街へ向かう / 24の休息地';details.appendChild(summary);for(const t of WORLD_TOWNS){const b=document.createElement('button');b.textContent='▦ '+t.name+' — ひと休み';b.onclick=()=>startJapan({...t,size:.18,heading:0});details.appendChild(b)}$('places').appendChild(details)}populatePlaces();
$('atlasCanvas').addEventListener('click',e=>{let c=$('atlasCanvas'),rect=c.getBoundingClientRect(),x=(e.clientX-rect.left)*2,y=(e.clientY-rect.top)*2,m=c._map;if(!m)return;let best=null,dist=55;for(const d of DESTINATIONS){let l=Math.hypot(m.tx(d.lon)-x,m.ty(d.lat)-y);if(l<dist){dist=l;best=d}}if(best)startJapan(best)});
function updateOptions(){$('labelsOption').textContent=options.labels?'オン':'オフ';$('labelsOption').setAttribute('aria-pressed',String(options.labels));$('soundOption').textContent=options.sound?'オン':'オフ';$('soundOption').classList.toggle('on',options.sound);$('qualityOption').textContent=options.quality==='light'?'軽量':'標準';$('motionOption').textContent=options.reduced?'オン':'オフ';$('motionOption').classList.toggle('on',options.reduced);$('contourOption').textContent=options.contour?'オン':'オフ';$('contourOption').classList.toggle('on',options.contour);$('timeOption').textContent=options.dusk?'夕':'朝';}
function save(){try{const data={version:1,gameVersion:VERSION,savedAt:new Date().toISOString(),options,stats:STATS,location:{mode:S.mode,lat:S.lat,lon:S.lon,x:S.x,z:S.z,region:S.region.id,size:S.sizeIndex}};localStorage.setItem(SAVE_KEY,JSON.stringify(data));$('saveInfo').textContent='移動先・記録・設定をこのブラウザに保存しています。';return data;}catch(e){$('saveInfo').textContent='この環境では自動保存を利用できません。書き出しを利用してください。';return{version:1,options,stats:STATS};}}
function downloadBlob(blob,filename){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000)}
async function snapshot(){if(!S.started)return;render(.016);const src=$('world'),c=document.createElement('canvas');c.width=src.width;c.height=src.height;const g=c.getContext('2d');g.drawImage(src,0,0);const k=c.width/1400,footer=Math.max(85,c.height*.15),grad=g.createLinearGradient(0,c.height-footer*2,0,c.height);grad.addColorStop(0,'#102d3400');grad.addColorStop(1,'#102d34ed');g.fillStyle=grad;g.fillRect(0,c.height-footer*2,c.width,footer*2);g.fillStyle='#f1e8d2';g.font=`${Math.max(20,32*k)}px sans-serif`;g.fillText('巨歩  KYOHO',c.width*.035,c.height-footer*.72);g.font=`${Math.max(10,13*k)}px sans-serif`;g.fillStyle='#c8d7c6';const label=S.mode==='demo'?'架空の練習島 — 日本の実地形ではありません':S.region.name+' / 国土地理院・地理院タイル（標高）を加工';g.fillText(label,c.width*.035,c.height-footer*.4);g.font=`${Math.max(9,11*k)}px sans-serif`;g.fillText(S.mode==='japan'?'出典 https://maps.gsi.go.jp/development/ichiran.html':'FICTIONAL TRAINING TERRAIN',c.width*.035,c.height-footer*.17);g.textAlign='right';g.font=`${Math.max(11,17*k)}px sans-serif`;g.fillStyle='#f1c288';g.fillText('身長 '+heightLabel(S.size)+'  /  '+S.distance.toFixed(1)+' km',c.width*.965,c.height-footer*.72);photoBlob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!photoBlob){tip('このブラウザでは画像を作成できませんでした。');return}if(photoURL)URL.revokeObjectURL(photoURL);photoURL=URL.createObjectURL(photoBlob);$('snapshotImage').src=photoURL;modal('photoModal');}
class Sound{
 constructor(){this.ctx=null;this.enabled=options.sound;this.isQuiet=false;this.lastStep=0}
 start(){if(!options.sound)return;try{if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=this.ctx=new C;this.master=c.createGain();this.master.gain.value=.22;this.master.connect(c.destination);const noise=c.createBuffer(1,c.sampleRate*3,c.sampleRate);let d=noise.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.7;this.noiseSource=c.createBufferSource();this.noiseSource.buffer=noise;this.noiseSource.loop=true;const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=550;this.windGain=c.createGain();this.windGain.gain.value=.018;this.noiseSource.connect(filter);filter.connect(this.windGain);this.windGain.connect(this.master);this.noiseSource.start();for(const f of[110,164.814]){let o=c.createOscillator(),v=c.createGain();o.type='sine';o.frequency.value=f;v.gain.value=.012;o.connect(v);v.connect(this.master);o.start()}}this.ctx.resume();this.master.gain.setTargetAtTime(options.sound?.22:0,this.ctx.currentTime,.2);}catch{}}
 quiet(v){this.isQuiet=v;if(this.ctx)this.master.gain.setTargetAtTime(!options.sound?0:v?.06:.22,this.ctx.currentTime,.25)}
 tone(f,duration=.3,gain=.15,type='sine'){if(!this.ctx||!options.sound)return;const c=this.ctx,t=c.currentTime,o=c.createOscillator(),v=c.createGain();o.type=type;o.frequency.setValueAtTime(f,t);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(gain,t+.012);v.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(v);v.connect(this.master);o.start(t);o.stop(t+duration+.02)}
 chime(i){const f=[293.66,329.63,392,440,523.25][i%5];this.tone(f,.65,.15);setTimeout(()=>this.tone(f*1.5,.8,.08),80)}
 step(h){if(S.time-this.lastStep<.14)return;this.lastStep=S.time;this.tone(Math.max(27,72-h*2),.12,.12)}
 land(h){this.tone(Math.max(25,55-h),.32,.24);this.tone(104,.12,.055)}
 jump(){this.tone(147,.28,.10)}
 wind(v,glide){if(this.ctx&&this.windGain)this.windGain.gain.setTargetAtTime(.018+v*.08+(glide?.065:0),this.ctx.currentTime,.3)}
}
const audio=new Sound;
// All input is scoped to active play; no pointer-lock requirement on mobile or desktop.
window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;const prevent=['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'];if(prevent.includes(e.code))e.preventDefault();if(S.modal){if(e.code==='Escape'&&S.modal!=='loading')modal(null);return;}if(!S.started){if(e.code==='Enter')startDemo();return}input.keys.add(e.code);lastInput=S.time;if(e.repeat)return;if(e.code==='Space')requestJump();else if(e.code==='KeyE')setSize((S.sizeIndex+1)%4);else if(['Digit1','Digit2','Digit3','Digit4'].includes(e.code))setSize(+e.code.slice(-1)-1);else if(e.code==='KeyM')modal('mapModal');else if(e.code==='KeyP')snapshot();else if(e.code==='Escape')modal('settings');else if(e.code==='KeyR'){S.auto=!S.auto;tip(S.auto?'自動走行中。J / Lキーやドラッグで方向を変えます。Rでも停止できます。':'自動走行を停止しました。',3)}else if(e.code==='KeyF')toggleFullscreen();});
window.addEventListener('keyup',e=>input.keys.delete(e.code));window.addEventListener('blur',()=>{input.keys.clear();input.jump=input.dash=false;input.joyX=input.joyY=0;S.auto=false;if(S.started&&!S.modal)modal('settings')});document.addEventListener('visibilitychange',()=>{if(document.hidden&&S.started&&!S.modal)modal('settings')});
$('world').addEventListener('pointerdown',e=>{if(!S.started||S.modal)return;input.drag=true;input.dragId=e.pointerId;input.lastX=e.clientX;input.lastY=e.clientY;$('world').setPointerCapture(e.pointerId);lastInput=S.time;});
$('world').addEventListener('pointermove',e=>{if(!input.drag||e.pointerId!==input.dragId)return;let dx=e.clientX-input.lastX,dy=e.clientY-input.lastY;S.camYaw-=dx*.005;S.camPitch=clamp(S.camPitch+dy*.0035,-.07,.90);input.lastX=e.clientX;input.lastY=e.clientY;lastInput=S.time;});
function endDrag(){input.drag=false;input.dragId=null}$('world').addEventListener('pointerup',endDrag);$('world').addEventListener('pointercancel',endDrag);$('world').addEventListener('contextmenu',e=>e.preventDefault());$('world').addEventListener('wheel',e=>{if(!S.started||S.modal)return;e.preventDefault();S.camPitch=clamp(S.camPitch+e.deltaY*.0006,-.07,.90)},{passive:false});
const stick=$('joystick');let joyId=null;function joy(e){const r=stick.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),max=r.width*.32,len=Math.hypot(dx,dy),factor=len>max?max/len:1,x=dx*factor,y=dy*factor;input.joyX=x/max;input.joyY=y/max;$('stick').style.transform=`translate(${x}px,${y}px)`;lastInput=S.time;}
stick.addEventListener('pointerdown',e=>{joyId=e.pointerId;stick.setPointerCapture(joyId);joy(e);e.preventDefault()});stick.addEventListener('pointermove',e=>{if(e.pointerId===joyId)joy(e)});function releaseJoy(){joyId=null;input.joyX=input.joyY=0;$('stick').style.transform=''}stick.addEventListener('pointerup',releaseJoy);stick.addEventListener('pointercancel',releaseJoy);
for(const[id,key]of[['touchJump','jump'],['touchDash','dash']]){const b=$(id);b.addEventListener('pointerdown',e=>{b.setPointerCapture(e.pointerId);input[key]=true;if(key==='jump')requestJump();audio.start();e.preventDefault()});const release=()=>input[key]=false;b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);}
$('startDemo').onclick=()=>startDemo();$('startJapan').onclick=()=>{let d=DESTINATIONS[0];if(saved?.location?.mode==='japan'&&Number.isFinite(saved.location.lat)&&Number.isFinite(saved.location.lon)&&saved.location.lat>20&&saved.location.lat<46.7&&saved.location.lon>122&&saved.location.lon<150){d={...(DESTINATIONS.find(d=>d.id===saved.location.region)||WORLD_TOWNS.find(d=>d.id===saved.location.region)||d),lat:saved.location.lat,lon:saved.location.lon,size:SIZES[clamp(saved.location.size??1,0,3)]};}startJapan(d)};
$('cancelLoad').onclick=()=>startDemo();$('retryLoad').onclick=()=>{if(S.pending)S.pending.startedAt=S.time;$('loadError').classList.add('hidden');terrain.retry()};$('mapBtn').onclick=()=>modal('mapModal');$('minimapWrap').onclick=()=>modal('mapModal');$('minimapWrap').onkeydown=e=>{if(e.key==='Enter')modal('mapModal')};$('photoBtn').onclick=()=>snapshot();$('menuBtn').onclick=()=>modal('settings');for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>modal(null);for(const b of $('sizeButtons').children)b.onclick=()=>setSize(+b.dataset.size);$('challengeBtn').onclick=startChallenge;$('autoBtn').onclick=()=>{S.auto=!S.auto;tip(S.auto?'自動走行中。視点を回すと、行き先も変わります。':'自動走行を停止しました。',4)};$('resumeBtn').onclick=()=>modal(null);$('helpBtn').onclick=()=>modal('help');$('titleBtn').onclick=()=>{save();modal(null);S.started=false;S.challenge=false;$('title').classList.remove('hidden');$('hud').classList.add('hidden');$('touchControls').classList.add('hidden');$('targetLabel').classList.add('hidden');$('tip').classList.add('hidden');$('bgCaption').textContent=S.mode==='demo'?'背景：架空の練習島 / 日本の実地形ではありません':'背景：'+S.region.name+' / 国土地理院の標高タイルを加工して表示';$('bgCaption').classList.remove('hidden');audio.quiet(true)};
$('labelsOption').onclick=()=>{options.labels=!options.labels;updateOptions();placesWorld.updateLabels(S,terrain,frame,options.labels);save()};
$('soundOption').onclick=()=>{options.sound=!options.sound;audio.start();audio.quiet(!!S.modal);updateOptions();save()};$('qualityOption').onclick=()=>{options.quality=options.quality==='light'?'standard':'light';updateOptions();save()};$('motionOption').onclick=()=>{options.reduced=!options.reduced;updateOptions();save()};$('contourOption').onclick=()=>{options.contour=!options.contour;updateOptions();save()};$('timeOption').onclick=()=>{options.dusk=!options.dusk;updateOptions();save()};
function toggleFullscreen(){if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>tip('全画面に切り替えられませんでした。'));else tip('このブラウザでは全画面切り替えを利用できません。',4)}$('fullscreenBtn').onclick=toggleFullscreen;
$('exportSave').onclick=()=>downloadBlob(new Blob([JSON.stringify(save(),null,2)],{type:'application/json'}),'kyoho-record.json');$('importSave').onclick=()=>$('saveFile').click();$('saveFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw Error('ファイルが大きすぎます');const data=JSON.parse(await f.text());if(data.version!==1||!data.stats)throw Error('巨歩の記録ファイルではありません');for(const mode of['demo','japan'])if(data.stats[mode])for(const name of['distance','best']){let value=data.stats[mode][name];if(Number.isFinite(value)&&value>=0&&value<1e10)STATS[mode][name]=value;}save();showToast('旅の記録を読み込みました。','JOURNEY RECORD',3);tip('距離と自己ベストを復元しました。',3)}catch(err){tip('読み込めませんでした：'+err.message,5)}e.target.value=''};
$('againBtn').onclick=startChallenge;$('freeBtn').onclick=()=>{modal(null);showToast('次は、決めずに走ろう。','FREE ROAM',3)};$('resultPhoto').onclick=snapshot;$('savePhoto').onclick=()=>{if(photoBlob)downloadBlob(photoBlob,'kyoho-'+S.mode+'-'+new Date().toISOString().slice(0,10)+'.png')};$('sharePhoto').onclick=async()=>{if(!photoBlob)return;const file=new File([photoBlob],'kyoho.png',{type:'image/png'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'巨歩 KYOHO',text:S.mode==='demo'?'巨大な身体で駆ける、架空の練習島。':'巨大な身体で、日本の実地形を駆ける。'});}else{$('savePhoto').click();tip('共有に対応していないため、画像を保存します。',4)}}catch(e){if(e.name!=='AbortError')tip('共有できませんでした。「画像を保存」をお使いください。',4)}};
window.addEventListener('resize',()=>{if(S.modal==='mapModal')drawAtlas()});$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();$('fatal').classList.remove('hidden');$('fatalMessage').textContent='3D描画が中断されました。再読み込みし、設定から「軽量」を選んでください。';save()});
function loop(){const now=performance.now()/1000,rawDt=Math.max(.001,now-lastNow),dt=Math.min(rawDt,.5);lastNow=now;S.time+=dt;try{pollLoading();const steps=Math.ceil(dt/.025);for(let i=0;i<steps;i++)updateMovement(dt/steps);render(dt);if(S.time-lastUI>.12){lastUI=S.time;updateUI()}if(S.time>toastUntil)$('toast').classList.remove('show');if(S.time>tipUntil)$('tip').classList.add('hidden');if(S.started&&S.time-lastSave>5){lastSave=S.time;save()}fpsCounter++;fpsElapsed+=rawDt;if(fpsElapsed>2){currentFps=Math.round(fpsCounter/fpsElapsed);if(currentFps<26)autoResolution=Math.max(.58,autoResolution*.84);else if(currentFps>52)autoResolution=Math.min(1,autoResolution*1.05);fpsElapsed=0;fpsCounter=0;$('fps').textContent=currentFps+' FPS · '+renderer.draws+' draws · '+Math.round(renderer.tris/1000)+'k triangles';}}catch(e){console.error(e);$('fatal').classList.remove('hidden');$('fatalMessage').textContent='描画中にエラーが発生しました：'+e.message;return;}requestAnimationFrame(loop)}
window.KYOHO={version:VERSION,places:placesWorld,placeData:{mountains:WORLD_MOUNTAINS,towns:WORLD_TOWNS},state:S,terrain,renderer,options,stats:STATS,startDemo,startJapan,setSize,startChallenge,finishChallenge,snapshot,getRoute:()=>route,ground:demoHeight,decodeDEM,geo:{ecef,frameAt,localGeo,offsetLL,haversine,tileXY,tileLL},step:dt=>updateMovement(dt),showFPS:()=>{$('fps').style.display='block'},getFPS:()=>currentFps};
requestAnimationFrame(loop);
})();
